PizzaHouseShop/PizzaHouseShop/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PizzaHouseShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PizzaHouseShop/PizzaHouseShop/Controllers/PizzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PizzaHouseShop.Interfaces;
using PizzaHouseShop.Models;
using PizzaHouseShop.ViewModel;

namespace PizzaHouseShop.Controllers
{
    public class PizzaController : Controller
    {
        private readonly IPizzaRepository _pizzaRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PizzaController(IPizzaRepository pizzaRepository, ICategoryRepository categoryRepository)
        {
            _pizzaRepository = pizzaRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            IEnumerable<Pizza> pizzas;
            string currentCategory = string.Empty;

            if(string.IsNullOrEmpty(category))
            {
                pizzas = _pizzaRepository.Pizzas.OrderBy(p => p.PizzaId);
                currentCategory = "All pizzas";
            }
            else
            {
                pizzas = _pizzaRepository.Pizzas.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.PizzaId);
                currentCategory = _categoryRepository.Categorues.FirstOrDefault(c => c.CategoryName == category).CategoryName;
            }
            return View(new PizzaListViewModel
            {
                Pizzas = pizzas,
                CurrentCategory = currentCategory
            });
        }

        public IActionResult Details(int id)
        {
            var pizza = _pizzaRepository.GetPizzaById(id);
            if(pizza == null)
            {
                return NotFound();
            }
            return View(pizza);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

PizzaHouseShop/PizzaHouseShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PizzaHouseShop.Interfaces;
using PizzaHouseShop.Models;
using PizzaHouseShop.ViewModel;

namespace PizzaHouseShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPizzaRepository _pizzaRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IPizzaRepository pizzaRepository, ShoppingCart shoppingCart)
        {
            _pizzaRepository = pizzaRepository;
            _shoppingCart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart= _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }
        public RedirectToActionResult AddToShoppingCart(int pizzaId)
        {
            var selectedPizza = _pizzaRepository.Pizzas.FirstOrDefault(p => p.PizzaId == pizzaId);

            if (selectedPizza != null)
            {
                _shoppingCart.AddToCart(selectedPizza, 1);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromShoppingCart( int pizzaId)
        {
            var selectedPizza = _pizzaRepository.Pizzas.FirstOrDefault(p => p.PizzaId == pizzaId);
            if(selectedPizza != null)
            {
                _shoppingCart.RemoveFromCart(selectedPizza);
            }
            return RedirectToAction("Index");
        }
    }
}

PizzaHouseShop/PizzaHouseShop/Views/Shared/Carousel.cshtml
<link rel="stylesheet" href="~/css/Shared_Carousel.css" />
<div id="carouselExampleIndicators" class="carousel slide Carousel-Div" data-bs-ride="carousel">
    <ol class="carousel-indicators">
        <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
        <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
        <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="/Images/Menu/Ham_pizza.png" alt="First slide" />
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/Images/Menu/Extra_Cheese_pizza.png" alt="Second slide" />
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/Images/Menu/Fresh_Brasil_pizza.png" alt="Third slide" />
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="/Images/Menu/Sausage_pizza.png" alt="Fourth slide" />
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

PizzaHouseShop/PizzaHouseShop/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if(SignInManager.IsSignedIn(User))
{
	<form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
		<ul class="navbar-nav navbar-right">
			<li><a class="nav-link text-dark" href="javascript:document.getElementById('logoutForm').submit()">Log off</li>
		</ul>
	</form>
}
else
{
	<ul class="navbar-nav navbar-right">
		<li><a class="nav-link text-dark" id="registerLink" asp-controller="Account" asp-action="Register">Register</a></li>
		<li><a class="nav-link text-dark" id="loginLink" asp-controller="Account" asp-action="Login">Log in</a></li>
	</ul>
}

PizzaHouseShop/PizzaHouseShop/Views/Shared/PizzaOverviewSummary.cshtml
@model Pizza 
<link rel="stylesheet" href="~/css/Shared_PizzaOverviewSummary.css" />

<div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="@Model.ImageThumbnailUrl"/ style=" width: 200px; height: 200px;">
                <div class="caption">
                    <h5 class="pull-right">@Model.Price.ToString("c")</h5>
                    <h5>
                        <a asp-controller="Pizza" asp-action="Details" asp-route-id="@Model.PizzaId">@Model.Name</a>
                    </h5>
                    <p>@Model.ShortDescription</p>
                </div>
                <div class="addToCart">
                    <p class="button btn-sm">
                        <a class="btn btn-primary"
                           asp-controller="ShoppingCart"
                           asp-action="AddToShoppingCart"
                           asp-route-pizzaId="@Model.PizzaId">Add to Cart</a>
                    </p>
                </div>
            </div>
        </div>
        <br />

PizzaHouseShop/PizzaHouseShop/Views/Shared/PizzasOfTheWeekSummary.cshtml
@model Pizza
<link rel="stylesheet" href="~/css/Shared_PizzasOfTheWeekSummary.css" />

<div class="col-12 col-md-8 col-lg-6 mx-auto">
	<div class="thumbnail">
		<img src="@Model.ImageThumbnailUrl" alt="" />
		<div class="caption">
			<h5 class="pull-right">@Model.Price.ToString("c")</h5>
			<h5>
				<a asp-controller="Pizza"
				   asp-action="Details"
				   asp-route-id="@Model.PizzaId">@Model.Name</a>
			</h5>
			<p>@Model.ShortDescription</p>
		</div>
		<div class="addToCart">
			<p class="button btn-sm">
				<a class="btn btn-primary"
				   asp-controller="ShoppingCart"
				   asp-action="AddToShoppingCart"
				   asp-route-pizzaId="@Model.PizzaId">Add to Cart</a>
			</p>
		</div>
	</div>
</div>

PizzaHouseShop/PizzaHouseShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaHouseShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PizzaHouseShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PizzaHouseShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Html.PartialAsync("LoginPartial")
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Contact" asp-action="Index">Contact Us</a>
                        </li>
                        @await Component.InvokeAsync("CategoryMenu")
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PizzaHouseShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @*Za Carousel :*@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRnNKFF3n5X6gJIHp0ODTwE3U34xFDKAnCGTdJwJ5" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-9/J+LWBLQLwoOZCTKppFefJuj5qeqPvQ8aMf3db5rHtbF9pUmIG/TiGSZ8Ew+sEf" crossorigin="anonymous"></script>
</body>
</html>